steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ez2source:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ez2source:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'ez2source'
    - '--image'
    - 'gcr.io/$PROJECT_ID/ez2source:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'PORT=8080'
    - '--set-secrets'
    - 'DATABASE_URL=database-url:latest,SESSION_SECRET=session-secret:latest,OPENAI_API_KEY=openai-api-key:latest'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--timeout'
    - '300'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/ez2source:$COMMIT_SHA'

# Configure build timeout
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'